[build]
builder = "dockerfile"
dockerfilePath = "back/Dockerfile.prod"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port 8000 --workers 2"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
