"""add_implementation_resources_column

Revision ID: 1d8ec74fe5de
Revises: 524ef355c7be
Create Date: 2026-01-20 18:40:57.521804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8ec74fe5de'
down_revision: Union[str, Sequence[str], None] = '524ef355c7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_hands_on', sa.Column('implementation_resources', sa.JSON(), nullable=True, comment='実装済みリソース {apis: [], components: [], services: [], summary: str}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_hands_on', 'implementation_resources')
    # ### end Alembic commands ###
