"""add_interactive_hands_on_fields

Revision ID: 524ef355c7be
Revises: 
Create Date: 2026-01-20 13:22:22.862375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524ef355c7be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    generation_mode_enum = sa.Enum('batch', 'interactive', name='generation_mode_enum')
    generation_state_enum = sa.Enum('pending', 'generating', 'waiting_input', 'completed', name='generation_state_enum')
    generation_mode_enum.create(op.get_bind(), checkfirst=True)
    generation_state_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('task_hands_on', sa.Column('generation_mode', generation_mode_enum, nullable=False, server_default='batch', comment='生成モード'))
    op.add_column('task_hands_on', sa.Column('generation_state', generation_state_enum, nullable=False, server_default='pending', comment='生成状態'))
    op.add_column('task_hands_on', sa.Column('user_interactions', sa.JSON(), nullable=True, comment='ユーザーの選択・入力履歴 [{type, choice_id, selected, user_note}]'))
    op.add_column('task_hands_on', sa.Column('session_id', sa.String(length=50), nullable=True, comment='インタラクティブ生成セッションID'))
    op.create_index(op.f('ix_task_hands_on_session_id'), 'task_hands_on', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_hands_on_session_id'), table_name='task_hands_on')
    op.drop_column('task_hands_on', 'session_id')
    op.drop_column('task_hands_on', 'user_interactions')
    op.drop_column('task_hands_on', 'generation_state')
    op.drop_column('task_hands_on', 'generation_mode')

    # Drop enum types
    sa.Enum(name='generation_state_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='generation_mode_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
