[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "celery -A celery_app worker --loglevel=info --concurrency=2 --max-tasks-per-child=100"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
