services:
  hackathon_support_agent:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/hackathon_support_agent:cached
    command: ["tail", "-f", "/dev/null"]

  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspaces/hackathon_support_agent:cached
    env_file:
      - ../back/.env
    working_dir: /workspaces/hackathon_support_agent/back
    depends_on:
      - db
      - redis
    command: python app.py

  frontend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspaces/hackathon_support_agent:cached
    env_file:
      - ../front/.env
    working_dir: /workspaces/hackathon_support_agent/front
    depends_on:
      - backend
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hack_helper
      POSTGRES_PASSWORD: hackathon
      POSTGRES_DB: hackathon_support_agent

  # Phase 3: Redis (Celery broker & result backend)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Phase 3: Celery Worker (ハンズオン生成)
  celery-worker:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - ../back/.env
    environment:
      - DATABASE_URL=postgresql://hack_helper:hackathon@db/hackathon_support_agent
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ..:/workspaces/hackathon_support_agent:cached
    working_dir: /workspaces/hackathon_support_agent/back
    command: celery -A celery_app worker --loglevel=info --concurrency=3

  # Phase 3: Flower (Celery monitoring UI)
  flower:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - redis
      - celery-worker
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ..:/workspaces/hackathon_support_agent:cached
    working_dir: /workspaces/hackathon_support_agent/back
    command: celery -A celery_app flower --port=5555

volumes:
  postgres_data:
  redis_data:
