services:
  hackathon_support_agent:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/hackathon_support_agent:cashed
    command: ["tail", "-f", "/dev/null"]
  
  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hack_helper
      POSTGRES_PASSWORD: hackathon
      POSTGRES_DB: hackathon_support_agent

volumes:
  postgres_data:
