[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "docker-compose -f docker-compose.railway.yml up"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100
numReplicas = 1

[[deploy.services]]
name = "api"
[[deploy.services]]
name = "celery-worker-1"
[[deploy.services]]
name = "celery-worker-2"
[[deploy.services]]
name = "celery-worker-3"
[[deploy.services]]
name = "redis"
[[deploy.services]]
name = "flower"
