import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from 'next-themes';
import DarkToggle from "@/components/theme-switcher";
import MountedWrapper from "@/components/MountedWrapper";
import GridEdge from "@/components/GridEgde";
import "./globals.css";
import { NextAuthProvider } from "@/libs/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <MountedWrapper>
            <ThemeProvider attribute="class" defaultTheme="system">
              <GridEdge>
                <DarkToggle />
                {children}
              </GridEdge>
            </ThemeProvider>
          </MountedWrapper>
        </NextAuthProvider>
      </body>
    </html>
  );
}
