name: Deploy Backend to Railway

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
      - '.github/workflows/deploy-backend.yml'
      - 'railway.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        run: |
          railway up --service hackathon-support-agent-production

      - name: Wait for deployment
        run: sleep 30

      - name: Health Check
        run: |
          curl -f ${{ secrets.BACKEND_URL }}/ || exit 1

      - name: Notify Success
        if: success()
        run: |
          echo "✅ Backend deployed successfully to Railway"
          echo "URL: ${{ secrets.BACKEND_URL }}"
