name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment
        working-directory: ./front
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build Project
        working-directory: ./front
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        working-directory: ./front
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN > deployment-url.txt

      - name: Get Deployment URL
        id: deployment
        working-directory: ./front
        run: |
          echo "url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT

      - name: Health Check
        run: |
          sleep 20
          curl -f ${{ steps.deployment.outputs.url }} || exit 1

      - name: Notify Success
        if: success()
        run: |
          echo "✅ Frontend deployed successfully to Vercel"
          echo "URL: ${{ steps.deployment.outputs.url }}"
