name: Deploy Backend to Railway

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
      - '.github/workflows/deploy-backend.yml'
      - 'railway.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link Railway Project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --environment production

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up

      - name: Wait for deployment
        run: sleep 30

      - name: Health Check
        run: |
          curl -f ${{ secrets.BACKEND_URL }}/ || exit 1

      - name: Notify Success
        if: success()
        run: |
          echo "✅ Backend deployed successfully to Railway"
          echo "URL: ${{ secrets.BACKEND_URL }}"
